### ISSUE TITLE
Feature flags are not updated using passenger

### ISSUE THREAD

**Issue by HenriqueKraemer** [Unleash/unleash-client-ruby#46]
The client doesn't update unleash feature flags information after the application boots using Phusion Passenger as the aplication server. I have tried with WEBrick and Puma, both work!

The [README](https://github.com/Unleash/unleash-client-ruby#add-initializer-if-using-puma) mentions an specific configuration to work on Puma, is there such configuration for Passenger?

**Environment:**
- Ruby (2.6.6)
- Ruby on Rails (5.2.5)
- Linux (Ubuntu 20.04.2 LTS)
- Passenger: Standalone

**Gems**
- passenger (6.0.7)
- unleash (3.2.2)

**Files**
```ruby
# config/initializers/unleash.rb
Unleash.configure do |config|
  config.url              = 'https://gitlab.com/api/v4/feature_flags/unleash/[SECRET]'
  config.instance_id      = '[SECRET]'
  config.app_name         = Rails.application.class.parent.to_s
  config.refresh_interval = 5
  config.logger           = Rails.logger
  config.environment      = Rails.env
end

UNLEASH = Unleash::Client.new
```

```yaml
# Passenger.json
{
  "port": "3000",
  "max_pool_size":"2",
  "min_instances": "2",
  "engine": "nginx",
  "disable_anonymous_telemetry": true
}
```
